version: '3'
services:

  postgres:
    image: "postgres:14.4-alpine"
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "myDB"
