version: '3'

services:
  
  postgres:
    build: "./db/Dockerfile"
    ports:
      - "5000:5432"
    
  server:
    build: .
    ports: 
      - "4000:4000"
    depends_on:
      - "postgres"
    restart: "on-failure"
    
